### ISSUE TITLE
[688] HTML で `<select>` 要素を `<hr>` でセパレートできるようになった

### ISSUE THREAD

**Issue by munierujp** [SaekiTominaga/blog.w0s.jp#265]
titleタグの中身がエスケープされていないようです。
![90A3D97E-B61B-4827-B4EA-4A8809E76865](https://user-images.githubusercontent.com/20086673/235838466-5237defe-136d-47e4-bfd2-cf889bf7c2af.jpeg)

**Comment by SaekiTominaga** [comment]
@munierujp ご連絡ありがとうございます。
添付画像は Twitter のものと思いますが、ソースコードを見ていただければお分かりのとおり、本ブログでは `<title>` も `<meta property="og:title">` も HTML エスケープは行っています。

![head 要素内のソース表示](https://user-images.githubusercontent.com/4138486/235840909-a39a4474-4850-4f70-8b01-00d6444d5215.png)

このような表示になってしまうのは Twitter 側の OGP 処理の問題かと思われ、記事タイトルに HTML や XML タグ表記が含まれる他の記事でも同じ状況となっています。

- Qiita の事例: https://twitter.com/kamikudakun/status/1622479487266074624
- Zenn の事例: https://twitter.com/cloud10designs/status/1625090748965347329


事象は以前から認識しているのですが、こちらとしてはどうしようもないことなので、これは現状ままとさせてください。

**Comment by munierujp** [comment]
@SaekiTominaga すみません、開発者ツール上でエスケープされていないように見えましたが、Chromeが気を使って変換しているだけでした。

<img width="460" alt="スクリーンショット 2023-05-03 16 13 53" src="https://user-images.githubusercontent.com/20086673/235852747-96ee9855-27a2-4b85-b3e5-847b13d0cb55.png">

Twitter側の問題であるとのことで承知しました。
ありがとうございます。
